In [1]:
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from bs4 import BeautifulSoup
import requests
import time
from selenium.common.exceptions import ElementNotVisibleException
import re
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException,InvalidArgumentException,InvalidCookieDomainException

# Q.1)  Scrape the details of most viewed videos on YouTube from Wikipedia

In [10]:
url =  'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-10-aa82ff34aace>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [11]:
rank =[]
name =[]
artist = []
views = []
date = []

In [12]:
for i in range(1,31):
    num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
    try:
      rank.append(num_tag.text)
    except NoSuchElementException:
      rank.append("-")
       
for i in range(1,31):
    vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
    try:
        name.append(vid_tag.text.strip().split('"')[1]) #appending only the names of the videos
    except NoSuchElementException:
        name.append("-")
 
for i in range(1,31):
    uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
    try:
        artist.append(uploadr_tag.text)
    except NoSuchElementException:
        artist.append("-")
        
for i in range(1,31):
    views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
    try:
        views.append(views_tag.text)
    except NoSuchElementException:
        views.append("-")
        
        
for i in range(1,31):
    date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")
    try:
        date.append(date_tag.text)
    except NoSuchElementException:
        date.append("-")

top_youtube_vids = {"Rank":rank,"Name":name,"Artist":artist,"Upload Date":date,"Views(Billions)":views}
Most_Viewed_Videos = pd.DataFrame(top_youtube_vids)

<ipython-input-12-3cef17f5501e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  num_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[1]")
<ipython-input-12-3cef17f5501e>:9: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  vid_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[2]")
<ipython-input-12-3cef17f5501e>:16: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  uploadr_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[3]")
<ipython-input-12-3cef17f5501e>:23: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  views_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[4]")
<ipython-input-12-3cef17f5501e>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  date_tag=driver.find_element_by_xpath(f"//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{i}]/td[5]")

In [13]:
Most_Viewed_Videos

,Rank,Name,Artist,Upload Date,Views(Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.60
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.61
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",5.87
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.51
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.32
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.61
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.53
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.47
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.35
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.27
10,11.,Gangnam Style,Psy,"July 15, 2012",4.24
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.67
12,13.,Sugar,Maroon 5,"January 14, 2015",3.58
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.48
14,15.,Roar,Katy Perry,"September 5, 2013",3.46
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.43
16,17.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.35
17,18.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.33
18,19.,Faded,Alan Walker,"December 3, 2015",3.17
19,20.,Dark Horse,Katy Perry,"February 20, 2014",3.17
20,21.,Girls Like You,Maroon 5,"May 31, 2018",3.16
21,22.,Lean On,Major Lazer,"March 22, 2015",3.12
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.12
23,24.,Shake It Off,Taylor Swift,"August 18, 2014",3.11
24,25.,Let Her Go,Passenger,"July 25, 2012",3.11
25,26.,Axel F,Crazy Frog,"June 16, 2009",3.08
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.00
27,28.,Mi Gente,J Balvin,"June 29, 2017",3.00
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",2.98
29,30.,Hello,Adele,"October 22, 2015",2.90

# Q.2) Scrape the details team India’s international fixtures from bcci.tv.

In [18]:
url =  'https://www.bcci.tv/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-18-b363e9ec01a6>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [19]:
intbtn = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]')
try:
    intbtn.click() 
except ElementNotInteractableException:
    pass
     
fixbtn =  driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')
try: 
    fixbtn.click()
except ElementNotInteractableException:
    pass

<ipython-input-19-17cc112ac8b4>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  intbtn = driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]')
<ipython-input-19-17cc112ac8b4>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  fixbtn =  driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/nav/ul/li[1]/div[2]/div/ul/li[1]/a')

In [40]:
Match_title = []
Series = []
Place = []
Date = []
Month=[]
Time = []

In [41]:
Match_title_tag = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
Series_tag = driver.find_elements_by_xpath("//div[@class='fixture__format-strip']")
Place_tag = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
Date_tag = driver.find_elements_by_xpath("//span[@class='fixture__date']")
Month_tag=driver.find_elements_by_xpath("//span[@class='fixture__month']")

<ipython-input-41-3e0bc2774b99>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Match_title_tag = driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
<ipython-input-41-3e0bc2774b99>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Series_tag = driver.find_elements_by_xpath("//div[@class='fixture__format-strip']")
<ipython-input-41-3e0bc2774b99>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Place_tag = driver.find_elements_by_xpath("//p[@class='fixture__additional-info']//span")
<ipython-input-41-3e0bc2774b99>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Date_tag = driver.find_elements_by_xpath("//span[@class='fixture__date']")
<ipython-input-41-3e0bc2774b99>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Month_tag=driver.find_elements_by_xpath("//span[@class='fixture__month']")

In [42]:
for m in Match_title_tag:
    try:
        Match_title.append(m.text)
    except NoSuchElementException:
        Match_title.append("-")
for s in Series_tag:
    try:
        Series.append(s.text.replace("\n"," "))
    except NoSuchElementException:
        Series.append("-")
        
for p in Place_tag:
    try:
        Place.append(p.text)
    except NoSuchElementException:
        Place.append("-")
        
for d in Date_tag:
    try:
        Date.append(d.text)
    except NoSuchElementException:
        Date.append("-")
for m in Month_tag:
    try:
        Month.append(m.text)
    except NoSuchElementException:
        Month.append("-")

In [55]:
url=[]
url_tag=driver.find_elements_by_xpath("//div[@class='js-list']/a")
for i in url_tag:
    url.append(i.get_attribute("href"))

<ipython-input-55-04fa13a2f1dd>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  url_tag=driver.find_elements_by_xpath("//div[@class='js-list']/a")

In [56]:
len(url)

10

In [57]:
Time=[]
for i in url:
    driver.get(i)
    time.sleep(3)
    Time_tag=driver.find_element_by_xpath("//span[@class='mc-header-scorebox__ist-time']")
    try:
        Time.append(Time_tag.text)
    except NoSuchElementException:
        Time.append("-")

<ipython-input-57-66459a551b3d>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Time_tag=driver.find_element_by_xpath("//span[@class='mc-header-scorebox__ist-time']")

In [58]:
print(len(Time),len(Match_title),len(Series),len(Place),len(Full_Date))

10 10 10 10 10

In [43]:
Full_Date=[]
for (item1,item2) in zip(Date,Month):
    Full_Date.append(item1+item2)

In [59]:
cricket = {'Match Title': Match_title,'Series':Series,'Place':Place,'Date':Full_Date,'Time':Time}

In [60]:
Cricket=pd.DataFrame(cricket)

In [61]:
Cricket

,Match Title,Series,Place,Date,Time
0,Match 42,T20I 2021 ICC MEN'S T20 WORLD CUP,"Dubai International Stadium, Dubai",08NOVEMBER,19:30 IST
1,1st T20I,T20I INDIA V NEW ZEALAND 2021,"Sawai Mansingh Stadium, Jaipur",17NOVEMBER,19:00 IST
2,2nd T20I,T20I INDIA V NEW ZEALAND 2021,"JSCA International Stadium Complex, Ranchi",19NOVEMBER,19:00 IST
3,3rd T20I,T20I INDIA V NEW ZEALAND 2021,"Eden Gardens, Kolkata",21NOVEMBER,19:00 IST
4,1st Test,TEST INDIA V NEW ZEALAND 2021,"Green Park, Kanpur",25NOVEMBER,09:30 IST
5,2nd Test,TEST INDIA V NEW ZEALAND 2021,"Wankhede Stadium, Mumbai",03DECEMBER,09:30 IST
6,1st ODI,ODI INDIA V WEST INDIES 2022,"Narendra Modi Stadium, Ahmedabad",06FEBRUARY,13:00 IST
7,2nd ODI,ODI INDIA V WEST INDIES 2022,"Sawai Mansingh Stadium, Jaipur",09FEBRUARY,13:00 IST
8,3rd ODI,ODI INDIA V WEST INDIES 2022,"Eden Gardens, Kolkata",12FEBRUARY,13:00 IST
9,1st T20I,T20I INDIA V WEST INDIES 2022,"Barabati Stadium, Cuttack",15FEBRUARY,19:00 IST

# Q.3) Scrape the details of selenium exception from guru99.com.

In [23]:
url =  'https://www.guru99.com/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-23-bbfa4c4ccf61>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [24]:
selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
try:
    selbtn.click() #clicking on Selenium button
except ElementNotInteractableException:
    pass
     
tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')
try: 
    tutbtn.click() #clicking on Exceptions Tutorial button
except ElementNotInteractableException:
    pass

<ipython-input-24-199655db7ae5>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  selbtn = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a')
<ipython-input-24-199655db7ae5>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  tutbtn =  driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong')

In [25]:
Name = []
desc = []

In [26]:
for i in range(2,43):
    Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
    try:
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
for i in range(2,43):    
    desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")
    try:
        desc.append(desc_tag.text)
    except NoSuchElementException:
        desc.append("-")

<ipython-input-26-3f1864b37f57>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[1]")
<ipython-input-26-3f1864b37f57>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath(f"//*[@id='post-1953']/div/div/table/tbody/tr[{i}]/td[2]")

In [27]:
Excep = {'Name': Name,'Description':desc}

In [28]:
Exception = pd.DataFrame(Excep)

In [29]:
Exception

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# Q.4) Scrape the details of State-wise GDP of India from statisticstime.com

In [30]:
url =  'http://statisticstimes.com/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-30-73a2c9511158>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [31]:
Eco_btn=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") #economy button
try:
    Eco_btn.click()#click economy button
except ElementNotInteractableException:
    pass

ind=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")#India button
try:
    ind.click()#click India button
except ElementNotInteractableException:
    pass

<ipython-input-31-98a725dfa0ba>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Eco_btn=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button") #economy button
<ipython-input-31-98a725dfa0ba>:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  ind=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")#India button

In [33]:
indstate=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")#GDP of Indian states
try:
    indstate.click()#click button
except ElementNotInteractableException:
    pass

<ipython-input-33-537c7363ea5a>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  indstate=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")#GDP of Indian states

In [34]:
Rank = []
State = []
GSDP_19 = []
GSDP_18 = []
Share_18 = []
GDP = []

In [35]:
for i in range(1,34):
    rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
    try:
        Rank.append(rank_tag.text)
    except NoSuchElementException:
        Rank.append("-")
for i in range(1,34):
    State_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
    try:
        State.append(State_tag.text)
    except NoSuchElementException:
        State.append("-")
        
for i in range(1,34):
    GSDP_19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
    try:
        GSDP_19.append(GSDP_19_tag.text)
    except NoSuchElementException:
        GSDP_19.append("-")

for i in range(1,34):
    GSDP_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
    try:
        GSDP_18.append(GSDP_18_tag.text)
    except NoSuchElementException:
        GSDP_18.append("-")

for i in range(1,34):
    Share_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
    try:
        Share_18.append(Share_18_tag.text)
    except NoSuchElementException:
        Share_18.append("-")
for i in range(1,34):
    GDP_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")
    try:
        GDP.append(GDP_tag.text)
    except NoSuchElementException:
        GDP.append("-")

<ipython-input-35-ebf01a67bf0e>:2: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  rank_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[1]")
<ipython-input-35-ebf01a67bf0e>:8: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  State_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[2]")
<ipython-input-35-ebf01a67bf0e>:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GSDP_19_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[3]")
<ipython-input-35-ebf01a67bf0e>:22: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GSDP_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[4]")
<ipython-input-35-ebf01a67bf0e>:29: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Share_18_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[5]")
<ipython-input-35-ebf01a67bf0e>:35: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  GDP_tag = driver.find_element_by_xpath(f"//*[@id='table_id']/tbody/tr[{i}]/td[6]")

In [36]:
GDP = {'Rank': Rank,'State':State,'GSDP at current price(19-20)':GSDP_19,'GSDP at current price(18-19)':GSDP_18,'Share(18-19)':Share_18,'GDP($ billion)':GDP}

In [37]:
GDPIND = pd.DataFrame(GDP)

In [38]:
GDPIND

,Rank,State,GSDP at current price(19-20),GSDP at current price(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Q.5) Scrape the details of trending repositories on Github.com.

In [39]:
url =  'https://github.com/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-39-fb14dbe159e6>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [40]:
Exp_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") #explore button
try:
    Exp_btn.click()#click explore button
except ElementNotInteractableException:
    pass
trnd=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")#Trending button
try:
    trnd.click()#click Trending button
except ElementNotInteractableException:
    pass

<ipython-input-40-668ee248eedd>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Exp_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary") #explore button
<ipython-input-40-668ee248eedd>:6: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  trnd=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")#Trending button

In [42]:
title = []
desc = []
count = []
url = []

In [43]:
title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

<ipython-input-43-cebc8138ba4d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [44]:
for r in title_tag:
    try:
       url.append(r.get_attribute("href"))
    except NoSuchElementException:
        url.append("-")

In [45]:
title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

<ipython-input-45-cebc8138ba4d>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  title_tag = driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")

In [46]:
for r in title_tag:
    try:
        title.append(r.text)
    except NoSuchElementException:
        title.append("-")

In [47]:
len(title)

25

In [48]:
for i in url:
    driver.get(i)
    time.sleep(5)
    try:   
        desc_tag = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        desc.append(desc_tag.text)
    except NoSuchElementException:
        desc.append('-')
    try:
        count_tag = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")
        count.append(count_tag.text)
    except NoSuchElementException:
        count.append('-')

<ipython-input-48-961a0165e5cb>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  desc_tag = driver.find_element_by_xpath("//p[@class='f4 mt-3']")
<ipython-input-48-961a0165e5cb>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  count_tag = driver.find_element_by_xpath("//a[contains(@href,'contributors')]/span")

In [49]:
lng = []

In [50]:
for i in url:
    driver.get(i)
    time.sleep(5)
    try:
        lng_tag = driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]")
        lng.append(lng_tag.text)
    except NoSuchElementException:
        lng.append('-')

<ipython-input-50-5694858f47c0>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  lng_tag = driver.find_element_by_xpath("//a[contains(@href,'search?')]/span[1]")

In [54]:
git = {'Repository title': title,'Repository description':desc,'Contributors count':count,'Language used':lng}

In [55]:
Git = pd.DataFrame(git)

In [56]:
Git

,Repository title,Repository description,Contributors count,Language used
0,misterokaygo / MapAssist,-,16,C#
1,questdb / questdb,An open source SQL database designed to proces...,50,Java
2,babysor / MockingBird,🚀AI拟声: 5秒内克隆您的声音并生成任意语音内容 Clone a voice in 5 s...,13,JavaScript
3,v2fly / v2ray-core,A platform for building proxies to bypass netw...,111,Go
4,foxsen / archbase,教科书《计算机体系结构基础》（胡伟武等，第三版）的开源版本,-,TeX
5,DrKLO / Telegram,Telegram for Android source,16,Java
6,files-community / Files,A modern file manager that pushes the boundari...,144,C#
7,Dreamacro / clash,A rule-based tunnel in Go.,67,Go
8,vandadnp / flutter-tips-and-tricks,A Collection of Flutter and Dart Tips and Tricks,-,Dart
9,233boy / v2ray,最好用的 V2Ray 一键安装脚本 & 管理脚本,-,Shell
10,aeon0 / botty,D2R Pixel Bot,2,Python
11,commaai / openpilot,openpilot is an open source driver assistance ...,254,Python
12,jwasham / coding-interview-university,A complete computer science study plan to beco...,226,-
13,ossu / computer-science,🎓 Path to a free self-taught education in Comp...,116,-
14,bitcoin / bitcoin,Bitcoin Core integration/staging tree,828,C++
15,solana-labs / solana,"Web-Scale Blockchain for fast, secure, scalabl...",223,Rust
16,getfotiaoqiang / download,佛跳墙官方版本下载页 翻墙 代理 科学上网 外网 加速器 梯子 路由,-,-
17,Kholid060 / automa,A chrome extension for automating your browser...,4,Vue
18,dockersamples / example-voting-app,Example Docker Compose app,32,C#
19,sherlock-project / sherlock,🔎 Hunt down social media accounts by username ...,135,Python
20,ACL4SSR / ACL4SSR,SSR 去广告ACL规则/SS完整GFWList规则/Clash规则碎片，Telegram频...,-,-
21,freefq / free,翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ray/trojan节点、蓝...,2,-
22,TandoorRecipes / recipes,"Application for managing recipes, planning mea...",64,HTML
23,CSSEGISandData / COVID-19,"Novel Coronavirus (COVID-19) Cases, provided b...",8,-
24,obsproject / obs-studio,OBS Studio - Free and open source software for...,461,C

# Q.6) Scrape the details of top 100 songs on billiboard.com.

In [62]:
url =  'https://www.billboard.com/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-62-36533f068f4e>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [63]:
top100_btn=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/nav/ul/li[3]/a") #hot100 button
try:
    top100_btn.click()#click explore button
except ElementNotInteractableException:
    pass

<ipython-input-63-e85d21a7e62f>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  top100_btn=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/nav/ul/li[3]/a") #hot100 button

In [81]:
#scraping Last week rank
last_week=[]
try:
    L_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in L_tag:
        last_week.append(i.text)
except NoSuchElementException:#handling no such element exception
    last_week.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    last_week.append('No details available')

<ipython-input-81-2c20f727258d>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  L_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")

In [82]:
name=[]
#scraping song name
try:
    n_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in n_tag:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')

<ipython-input-82-3990caf56952>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  n_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")

In [83]:
artist=[]
#scraping artist name
try:
    a_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in a_tag:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')

<ipython-input-83-649bb4ddd65d>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  a_tag=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")

In [84]:
peak_rank=[]
#scraping peak rank
try:
    p_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in p_tag:
        peak_rank.append(i.text)
except NoSuchElementException:
    peak_rank.append('No details available')
except StaleElementReferenceException:
    peak_rank.append('No details available')

<ipython-input-84-7aa682cd4dbf>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  p_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")

In [85]:
week=[]
#scraping weeks on board
try:
    w_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in w_tag:
        week.append(i.text)
except NoSuchElementException:
    week.append('No details available')
except StaleElementReferenceException:
    week.append('No details available')

<ipython-input-85-c45e4554c0b2>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  w_tag=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")

In [87]:
df = pd.DataFrame({'song name':name,'Artist_name':artist,'Last week rank':last_week,'Peak rank':peak_rank,'Weeks on board':week})
Top_100_Songs=df[:100]
Top_100_Songs

,song name,Artist_name,Last week rank,Peak rank,Weeks on board
0,Certified Lover Boy,Drake,2,1,8
1,Dangerous: The Double Album,Morgan Wallen,8,1,42
2,Planet Her,Doja Cat,7,2,18
3,"Sincerely, Kentrell",YoungBoy Never Broke Again,6,1,5
4,Sour,Olivia Rodrigo,9,1,23
...,...,...,...,...,...
95,Divinely Uninspired To A Hellish Extent,Lewis Capaldi,94,20,128
96,The Essential Michael Jackson,Michael Jackson,97,31,372
97,Legend: The Best Of...,Bob Marley And The Wailers,96,5,702
98,Metallica,Metallica,78,1,631
99,La 167,Farruko,80,26,4

# Q.7) Scrape the details of Data science recruiters from naukri.com

In [63]:
url =  'https://www.naukri.com/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-63-629335105d1a>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [64]:
recruit_btn=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div") #recruiters button
try:
    recruit_btn.click()
except ElementNotInteractableException:
    pass
driver.switch_to.window(driver.window_handles[1])

<ipython-input-64-332f344499ad>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  recruit_btn=driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/ul[1]/li[2]/a/div") #recruiters button

In [65]:
jobsearch = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')
jobsearch

<ipython-input-65-e7a6ff30f764>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  jobsearch = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input')

In [66]:
jobsearch.send_keys("Data science")

In [67]:
srchbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')
srchbtn.click()

<ipython-input-67-9efe354a009f>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  srchbtn = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button')

In [68]:
Name = []
Designation = []
Company = []
Skills = []

In [69]:
Name_tag = driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
Designation_tag = driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
Company_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
Skills_tag = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
Location_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/span/small")

<ipython-input-69-c422f168d8c0>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Name_tag = driver.find_elements_by_xpath("//a[@class='ellipsis']/span")
<ipython-input-69-c422f168d8c0>:2: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Designation_tag = driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
<ipython-input-69-c422f168d8c0>:3: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Company_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[2]")
<ipython-input-69-c422f168d8c0>:4: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Skills_tag = driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
<ipython-input-69-c422f168d8c0>:5: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  Location_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/span/small")

In [70]:
for n in Name_tag:
    try:
        Name.append(n.text)
    except NoSuchElementException:
        Name.append("-")
for d in Designation_tag:
    try:
        Designation.append(d.text)
    except NoSuchElementException:
        Designation.append("-")


for c in Company_tag:
    try:
        Company.append(c.text)
    except NoSuchElementException:
        Company.append("-")


for s in Skills_tag:
    try:
        Skills.append(s.text)
    except NoSuchElementException:
        Skills.append("-")

In [71]:
nameurl = []

In [72]:
name_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

<ipython-input-72-cae30aaffeb4>:1: DeprecationWarning: find_elements_by_* commands are deprecated. Please use find_elements() instead
  name_tag = driver.find_elements_by_xpath("//p[@class='highlightable']/a[1]")

In [73]:
for r in name_tag:
    try:
       nameurl.append(r.get_attribute("href"))
    except NoSuchElementException:
        nameurl.append("-")

In [74]:
Location = []

In [75]:
for i in nameurl:
    driver.get(i)
    time.sleep(5)
    try:   
        Location_tag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
        Location.append(Location_tag.text)
    except NoSuchElementException:
        Location.append('-')

<ipython-input-75-c1c707c7be6d>:5: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Location_tag = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")

In [76]:
jobs = {'Name': Name,'Designation':Designation,'Company':Company,'Skills they hire for':Skills,'Location':Location}

Jobs = pd.DataFrame(jobs)

Jobs

,Name,Designation,Company,Skills they hire for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Narasimha,Company Recruiter,Step Next Private Limited,"Data Modeling, Data Wrangling, seaborn, eda, p...",Hyderabad / Secunderabad
8,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
9,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
10,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
18,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
34,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
35,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",

# Q.8) Scrape the details of Highest selling novels

In [77]:
url =  ' https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-77-024342dbe973>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [78]:
Book= []
Author = []
Volumes = []
Publisher = []
Genre = []

In [79]:
for i in range(1,101):
    try:
        Book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
        Book.append(Book_tag.text)
    except NoSuchElementException:
        Book.append("-")
        
for i in range(1,101):
    try:
        Author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
        Author.append(Author_tag.text)
    except NoSuchElementException:
        Author.append("-")
        
for i in range(1,101):
    try:
        Volumes_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
        Volumes.append(Volumes_tag.text)
    except NoSuchElementException:
        Volumes.append("-")

for i in range(1,101):
    try:
        Publisher_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
        Publisher.append(Publisher_tag.text)
    except NoSuchElementException:
        Publisher.append("-")

for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

<ipython-input-79-ea65ca9fd5b7>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Book_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[2]")
<ipython-input-79-ea65ca9fd5b7>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Author_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[3]")
<ipython-input-79-ea65ca9fd5b7>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Volumes_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[4]")
<ipython-input-79-ea65ca9fd5b7>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Publisher_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[5]")
<ipython-input-79-ea65ca9fd5b7>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Genre_tag = driver.find_element_by_xpath(f"/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{i}]/td[6]")

In [80]:
Top100Books = {'Book name': Book,'Author name':Author,'Volumes sold':Volumes,'Publisher':Publisher,'Genre':Genre}

Top_100_Books = pd.DataFrame(Top100Books)

Top_100_Books

,Book name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q.9)Scrape the details most watched tv series of all time from imdb.com.

In [81]:
url =  'https://www.imdb.com/list/ls095964455/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-81-d3bcfd659623>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [82]:
Name = []
Year = []
Genre = []
Runtime = []
Ratings = []
Votes = []

In [83]:
for i in range(1,101):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,101):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")
        
for i in range(1,101):
    try:
        Genre_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]")
        Genre.append(Genre_tag.text)
    except NoSuchElementException:
        Genre.append("-")

for i in range(1,101):
    try:
        Runtime_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]")
        Runtime.append(Runtime_tag.text)
    except NoSuchElementException:
        Runtime.append("-")

for i in range(1,101):
    try:
        Ratings_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]")
        Ratings.append(Ratings_tag.text)
    except NoSuchElementException:
        Ratings.append("-")
for i in range(1,101):
    try:
        Votes_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[4]/span[2]")
        Votes.append(Votes_tag.text)
    except NoSuchElementException:
        Votes.append("-")

<ipython-input-83-3f1c83ef0f99>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/a")
<ipython-input-83-3f1c83ef0f99>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Year_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/h3/span[2]")
<ipython-input-83-3f1c83ef0f99>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Genre_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[5]")
<ipython-input-83-3f1c83ef0f99>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Runtime_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[1]/span[3]")
<ipython-input-83-3f1c83ef0f99>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Ratings_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/div[1]/div[1]/span[2]")
<ipython-input-83-3f1c83ef0f99>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Votes_tag = driver.find_element_by_xpath(f"/html/body/div[4]/div/div[2]/div[3]/div[1]/div/div[3]/div[3]/div[{i}]/div[2]/p[4]/span[2]")

In [84]:
Top100shows = {'Name': Name,'Year span':Year,'Genre':Genre,'Run time':Runtime,'Ratings':Ratings,'Votes':Votes}

Top_100_shows = pd.DataFrame(Top100shows)

Top_100_shows

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,895,197"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"926,507"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"910,481"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"272,452"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"232,863"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,279"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,117"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"179,334"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"37,558"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"210,930"

# Q.10) Details of Datasets from UCI machine learning repositories.

In [85]:
url =  'https://archive.ics.uci.edu/'
driver=webdriver.Chrome(r"C:\Users\shaha\Downloads\chromedriver_win32/chromedriver.exe")
driver.get(url)

<ipython-input-85-a0dfc1988f62>:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome('chromedriver.exe')

In [86]:
dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button
try:
    dtbtn.click() #clicking on view all data sets button
except ElementNotInteractableException:
    pass

<ipython-input-86-2953cdfaaa09>:1: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  dtbtn = driver.find_element_by_xpath('/html/body/table[2]/tbody/tr/td/span/b/a') #view all data sets button

In [87]:
Name = []
Datatype = []
Task = []
Attribute = []
instances = []
attribute_no = []
Year = []

In [88]:
for i in range(1,590):
    try:
        Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
        Name.append(Name_tag.text)
    except NoSuchElementException:
        Name.append("-")
        
for i in range(1,590):
    try:
        Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
        Datatype.append(Datatype_tag.text)
    except NoSuchElementException:
        Datatype.append("-")
        
for i in range(1,590):
    try:
        Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
        Task.append(Task_tag.text)
    except NoSuchElementException:
        Task.append("-")

for i in range(1,590):
    try:
        Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
        Attribute.append(Attribute_tag.text)
    except NoSuchElementException:
        Attribute.append("-")

for i in range(1,590):
    try:
        instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
        instances.append(instances_tag.text)
    except NoSuchElementException:
        instances.append("-")
for i in range(1,590):
    try:
        attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
        attribute_no.append(attribute_no_tag.text)
    except NoSuchElementException:
        Votes.append("-")
for i in range(1,590):
    try:
        Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")
        Year.append(Year_tag.text)
    except NoSuchElementException:
        Year.append("-")

<ipython-input-88-1132c95f86d6>:3: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Name_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[1]/table/tbody/tr/td[2]/p/b/a")
<ipython-input-88-1132c95f86d6>:10: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Datatype_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[2]/p")
<ipython-input-88-1132c95f86d6>:17: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Task_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[3]/p")
<ipython-input-88-1132c95f86d6>:24: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Attribute_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[4]/p")
<ipython-input-88-1132c95f86d6>:31: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  instances_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[5]/p")
<ipython-input-88-1132c95f86d6>:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  attribute_no_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[6]/p")
<ipython-input-88-1132c95f86d6>:43: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  Year_tag = driver.find_element_by_xpath(f"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{i}]/td[7]/p")

In [92]:
repo = {'Dataset name': Name,'Data type':Datatype,'Task':Task,'Attribute type':Attribute,'No of instances':instances,'No of attribute':attribute_no,'Year':Year}

RepoDF = pd.DataFrame(repo)
RepoDF.drop(index = 0,inplace = True)

In [93]:
RepoDF

,Dataset name,Data type,Task,Attribute type,No of instances,No of attribute,Year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021

# !!!!!! TAHNK YOU !!!!!!